# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\ROIInfoGui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ROIInfoWindow(object):
    def setupUi(self, ROIInfoWindow):
        ROIInfoWindow.setObjectName(_fromUtf8("ROIInfoWindow"))
        ROIInfoWindow.resize(503, 665)
        ROIInfoWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(ROIInfoWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_23 = QtGui.QLabel(self.centralwidget)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_23)
        self.lblROISet = QtGui.QLabel(self.centralwidget)
        self.lblROISet.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lblROISet.setFrameShape(QtGui.QFrame.WinPanel)
        self.lblROISet.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblROISet.setText(_fromUtf8(""))
        self.lblROISet.setObjectName(_fromUtf8("lblROISet"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lblROISet)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.lblROIType = QtGui.QLabel(self.centralwidget)
        self.lblROIType.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lblROIType.setFrameShape(QtGui.QFrame.WinPanel)
        self.lblROIType.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblROIType.setText(_fromUtf8(""))
        self.lblROIType.setObjectName(_fromUtf8("lblROIType"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lblROIType)
        self.label_25 = QtGui.QLabel(self.centralwidget)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_25)
        self.lblROIIndex = QtGui.QLabel(self.centralwidget)
        self.lblROIIndex.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lblROIIndex.setFrameShape(QtGui.QFrame.WinPanel)
        self.lblROIIndex.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblROIIndex.setText(_fromUtf8(""))
        self.lblROIIndex.setObjectName(_fromUtf8("lblROIIndex"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lblROIIndex)
        self.label_21 = QtGui.QLabel(self.centralwidget)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_21)
        self.txtd1 = QtGui.QLineEdit(self.centralwidget)
        self.txtd1.setObjectName(_fromUtf8("txtd1"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.txtd1)
        self.verticalLayout.addLayout(self.formLayout)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_15)
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_19)
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_16)
        self.txtXCenter = QtGui.QLineEdit(self.centralwidget)
        self.txtXCenter.setObjectName(_fromUtf8("txtXCenter"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtXCenter)
        self.txtYCenter = QtGui.QLineEdit(self.centralwidget)
        self.txtYCenter.setObjectName(_fromUtf8("txtYCenter"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtYCenter)
        self.txtZCenter = QtGui.QLineEdit(self.centralwidget)
        self.txtZCenter.setObjectName(_fromUtf8("txtZCenter"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.txtZCenter)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_6)
        self.leValue = QtGui.QLineEdit(self.centralwidget)
        self.leValue.setObjectName(_fromUtf8("leValue"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.leValue)
        self.verticalLayout.addLayout(self.formLayout_3)
        self.pbUpdate = QtGui.QPushButton(self.centralwidget)
        self.pbUpdate.setObjectName(_fromUtf8("pbUpdate"))
        self.verticalLayout.addWidget(self.pbUpdate)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.txtT1 = QtGui.QLineEdit(self.centralwidget)
        self.txtT1.setObjectName(_fromUtf8("txtT1"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtT1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.txtT2 = QtGui.QLineEdit(self.centralwidget)
        self.txtT2.setObjectName(_fromUtf8("txtT2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtT2)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.txtADC = QtGui.QLineEdit(self.centralwidget)
        self.txtADC.setObjectName(_fromUtf8("txtADC"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.txtADC)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_9)
        self.txtConcentration = QtGui.QLineEdit(self.centralwidget)
        self.txtConcentration.setObjectName(_fromUtf8("txtConcentration"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.txtConcentration)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_11)
        self.txtProtonDensity = QtGui.QLineEdit(self.centralwidget)
        self.txtProtonDensity.setObjectName(_fromUtf8("txtProtonDensity"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.txtProtonDensity)
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_14)
        self.lblAve = QtGui.QLineEdit(self.centralwidget)
        self.lblAve.setObjectName(_fromUtf8("lblAve"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.lblAve)
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_13)
        self.lblSd = QtGui.QLineEdit(self.centralwidget)
        self.lblSd.setObjectName(_fromUtf8("lblSd"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.lblSd)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lenVoxels = QtGui.QLineEdit(self.centralwidget)
        self.lenVoxels.setObjectName(_fromUtf8("lenVoxels"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.lenVoxels)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_3)
        self.leH = QtGui.QLineEdit(self.centralwidget)
        self.leH.setObjectName(_fromUtf8("leH"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.FieldRole, self.leH)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_4)
        self.leV = QtGui.QLineEdit(self.centralwidget)
        self.leV.setObjectName(_fromUtf8("leV"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.FieldRole, self.leV)
        self.label_29 = QtGui.QLabel(self.centralwidget)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_29)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.imvROI = ImageView(self.centralwidget)
        self.imvROI.setObjectName(_fromUtf8("imvROI"))
        self.verticalLayout_2.addWidget(self.imvROI)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        ROIInfoWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ROIInfoWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 503, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuUpdate_Values = QtGui.QMenu(self.menubar)
        self.menuUpdate_Values.setObjectName(_fromUtf8("menuUpdate_Values"))
        ROIInfoWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ROIInfoWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ROIInfoWindow.setStatusBar(self.statusbar)
        self.actionUpdate_values = QtGui.QAction(ROIInfoWindow)
        self.actionUpdate_values.setObjectName(_fromUtf8("actionUpdate_values"))
        self.menubar.addAction(self.menuUpdate_Values.menuAction())

        self.retranslateUi(ROIInfoWindow)
        QtCore.QMetaObject.connectSlotsByName(ROIInfoWindow)

    def retranslateUi(self, ROIInfoWindow):
        ROIInfoWindow.setWindowTitle(_translate("ROIInfoWindow", "ROI Information", None))
        self.label_23.setText(_translate("ROIInfoWindow", "ROI set", None))
        self.label.setText(_translate("ROIInfoWindow", "ROI type", None))
        self.label_25.setText(_translate("ROIInfoWindow", "ROI index", None))
        self.label_21.setText(_translate("ROIInfoWindow", "ROI diameter", None))
        self.label_15.setText(_translate("ROIInfoWindow", "X (mm)", None))
        self.label_19.setText(_translate("ROIInfoWindow", "Y (mm)", None))
        self.label_16.setText(_translate("ROIInfoWindow", "Z (mm)", None))
        self.label_6.setText(_translate("ROIInfoWindow", "Value", None))
        self.pbUpdate.setText(_translate("ROIInfoWindow", "update", None))
        self.label_5.setText(_translate("ROIInfoWindow", "T2 (ms)", None))
        self.label_7.setText(_translate("ROIInfoWindow", "ADC*1000 (mm2/s)", None))
        self.label_9.setText(_translate("ROIInfoWindow", "Concentration (mM)", None))
        self.label_11.setText(_translate("ROIInfoWindow", "proton density (%)", None))
        self.label_14.setText(_translate("ROIInfoWindow", "Ave signal", None))
        self.label_13.setText(_translate("ROIInfoWindow", "standard deviation", None))
        self.label_2.setText(_translate("ROIInfoWindow", "# voxels", None))
        self.label_3.setText(_translate("ROIInfoWindow", "Column", None))
        self.label_4.setText(_translate("ROIInfoWindow", "Row", None))
        self.label_29.setText(_translate("ROIInfoWindow", "T1 (ms)", None))
        self.menuUpdate_Values.setTitle(_translate("ROIInfoWindow", "Files", None))
        self.actionUpdate_values.setText(_translate("ROIInfoWindow", "Update values", None))

from pyqtgraph import ImageView
