# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\ROIInfoGui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ROIInfoWindow(object):
    def setupUi(self, ROIInfoWindow):
        ROIInfoWindow.setObjectName("ROIInfoWindow")
        ROIInfoWindow.resize(503, 665)
        ROIInfoWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(ROIInfoWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setObjectName("label_23")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.lblROISet = QtWidgets.QLabel(self.centralwidget)
        self.lblROISet.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblROISet.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lblROISet.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblROISet.setText("")
        self.lblROISet.setObjectName("lblROISet")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lblROISet)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lblROIType = QtWidgets.QLabel(self.centralwidget)
        self.lblROIType.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblROIType.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lblROIType.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblROIType.setText("")
        self.lblROIType.setObjectName("lblROIType")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lblROIType)
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setObjectName("label_25")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.lblROIIndex = QtWidgets.QLabel(self.centralwidget)
        self.lblROIIndex.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblROIIndex.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lblROIIndex.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblROIIndex.setText("")
        self.lblROIIndex.setObjectName("lblROIIndex")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lblROIIndex)
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.txtd1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtd1.setObjectName("txtd1")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtd1)
        self.verticalLayout.addLayout(self.formLayout)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setObjectName("label_19")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.txtXCenter = QtWidgets.QLineEdit(self.centralwidget)
        self.txtXCenter.setObjectName("txtXCenter")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtXCenter)
        self.txtYCenter = QtWidgets.QLineEdit(self.centralwidget)
        self.txtYCenter.setObjectName("txtYCenter")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtYCenter)
        self.txtZCenter = QtWidgets.QLineEdit(self.centralwidget)
        self.txtZCenter.setObjectName("txtZCenter")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtZCenter)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.leValue = QtWidgets.QLineEdit(self.centralwidget)
        self.leValue.setObjectName("leValue")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.leValue)
        self.verticalLayout.addLayout(self.formLayout_3)
        self.pbUpdate = QtWidgets.QPushButton(self.centralwidget)
        self.pbUpdate.setObjectName("pbUpdate")
        self.verticalLayout.addWidget(self.pbUpdate)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.txtT1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtT1.setObjectName("txtT1")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtT1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.txtT2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtT2.setObjectName("txtT2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtT2)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.txtADC = QtWidgets.QLineEdit(self.centralwidget)
        self.txtADC.setObjectName("txtADC")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtADC)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.txtConcentration = QtWidgets.QLineEdit(self.centralwidget)
        self.txtConcentration.setObjectName("txtConcentration")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtConcentration)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.txtProtonDensity = QtWidgets.QLineEdit(self.centralwidget)
        self.txtProtonDensity.setObjectName("txtProtonDensity")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtProtonDensity)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.lblAve = QtWidgets.QLineEdit(self.centralwidget)
        self.lblAve.setObjectName("lblAve")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lblAve)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.lblSd = QtWidgets.QLineEdit(self.centralwidget)
        self.lblSd.setObjectName("lblSd")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lblSd)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lenVoxels = QtWidgets.QLineEdit(self.centralwidget)
        self.lenVoxels.setObjectName("lenVoxels")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lenVoxels)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.leH = QtWidgets.QLineEdit(self.centralwidget)
        self.leH.setObjectName("leH")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.leH)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.leV = QtWidgets.QLineEdit(self.centralwidget)
        self.leV.setObjectName("leV")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.leV)
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setObjectName("label_29")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.imvROI = ImageView(self.centralwidget)
        self.imvROI.setObjectName("imvROI")
        self.verticalLayout_2.addWidget(self.imvROI)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        ROIInfoWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ROIInfoWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 503, 21))
        self.menubar.setObjectName("menubar")
        self.menuUpdate_Values = QtWidgets.QMenu(self.menubar)
        self.menuUpdate_Values.setObjectName("menuUpdate_Values")
        ROIInfoWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ROIInfoWindow)
        self.statusbar.setObjectName("statusbar")
        ROIInfoWindow.setStatusBar(self.statusbar)
        self.actionUpdate_values = QtWidgets.QAction(ROIInfoWindow)
        self.actionUpdate_values.setObjectName("actionUpdate_values")
        self.menubar.addAction(self.menuUpdate_Values.menuAction())

        self.retranslateUi(ROIInfoWindow)
        QtCore.QMetaObject.connectSlotsByName(ROIInfoWindow)

    def retranslateUi(self, ROIInfoWindow):
        _translate = QtCore.QCoreApplication.translate
        ROIInfoWindow.setWindowTitle(_translate("ROIInfoWindow", "ROI Information"))
        self.label_23.setText(_translate("ROIInfoWindow", "ROI set"))
        self.label.setText(_translate("ROIInfoWindow", "ROI type"))
        self.label_25.setText(_translate("ROIInfoWindow", "ROI index"))
        self.label_21.setText(_translate("ROIInfoWindow", "ROI diameter"))
        self.label_15.setText(_translate("ROIInfoWindow", "X (mm)"))
        self.label_19.setText(_translate("ROIInfoWindow", "Y (mm)"))
        self.label_16.setText(_translate("ROIInfoWindow", "Z (mm)"))
        self.label_6.setText(_translate("ROIInfoWindow", "Value"))
        self.pbUpdate.setText(_translate("ROIInfoWindow", "update"))
        self.label_5.setText(_translate("ROIInfoWindow", "T2 (ms)"))
        self.label_7.setText(_translate("ROIInfoWindow", "ADC*1000 (mm2/s)"))
        self.label_9.setText(_translate("ROIInfoWindow", "Concentration (mM)"))
        self.label_11.setText(_translate("ROIInfoWindow", "proton density (%)"))
        self.label_14.setText(_translate("ROIInfoWindow", "Ave signal"))
        self.label_13.setText(_translate("ROIInfoWindow", "standard deviation"))
        self.label_2.setText(_translate("ROIInfoWindow", "# voxels"))
        self.label_3.setText(_translate("ROIInfoWindow", "Column"))
        self.label_4.setText(_translate("ROIInfoWindow", "Row"))
        self.label_29.setText(_translate("ROIInfoWindow", "T1 (ms)"))
        self.menuUpdate_Values.setTitle(_translate("ROIInfoWindow", "Files"))
        self.actionUpdate_values.setText(_translate("ROIInfoWindow", "Update values"))

from pyqtgraph import ImageView
