# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ROIPropertiesGui.ui'
#
# Created: Sun Jan 11 10:19:26 2015
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

try:
  from PyQt4 import QtGui, QtCore
except:
  from PyQt5 import QtGui, QtCore

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ROIPropertiesGui(object):
    def setupUi(self, ROIPropertiesGui):
        ROIPropertiesGui.setObjectName(_fromUtf8("ROIPropertiesGui"))
        ROIPropertiesGui.resize(1343, 1119)
        self.centralwidget = QtGui.QWidget(ROIPropertiesGui)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tblT1 = QtGui.QTableWidget(self.centralwidget)
        self.tblT1.setGeometry(QtCore.QRect(35, 110, 1161, 231))
        self.tblT1.setMinimumSize(QtCore.QSize(931, 0))
        self.tblT1.setObjectName(_fromUtf8("tblT1"))
        self.tblT1.setColumnCount(14)
        self.tblT1.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.tblT1.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblT1.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblT1.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tblT1.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tblT1.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tblT1.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tblT1.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblT1.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblT1.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tblT1.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tblT1.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tblT1.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tblT1.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tblT1.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tblT1.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tblT1.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tblT1.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tblT1.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tblT1.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tblT1.setHorizontalHeaderItem(13, item)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(45, 120, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.tblT2 = QtGui.QTableWidget(self.centralwidget)
        self.tblT2.setGeometry(QtCore.QRect(35, 360, 1161, 231))
        self.tblT2.setMinimumSize(QtCore.QSize(931, 0))
        self.tblT2.setObjectName(_fromUtf8("tblT2"))
        self.tblT2.setColumnCount(14)
        self.tblT2.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.tblT2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2.setHorizontalHeaderItem(13, item)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(45, 370, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setMouseTracking(True)
        self.label_2.setAcceptDrops(True)
        self.label_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(25, 5, 87, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(400, 5, 49, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.txtField = QtGui.QTextEdit(self.centralwidget)
        self.txtField.setGeometry(QtCore.QRect(390, 30, 71, 21))
        self.txtField.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtField.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtField.setObjectName(_fromUtf8("txtField"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(262, 5, 55, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.txtComment = QtGui.QTextEdit(self.centralwidget)
        self.txtComment.setGeometry(QtCore.QRect(185, 30, 196, 36))
        self.txtComment.setObjectName(_fromUtf8("txtComment"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(485, 5, 95, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.txtTemperature = QtGui.QTextEdit(self.centralwidget)
        self.txtTemperature.setGeometry(QtCore.QRect(485, 30, 71, 21))
        self.txtTemperature.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtTemperature.setObjectName(_fromUtf8("txtTemperature"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(610, 5, 86, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.txtnROIsets = QtGui.QTextEdit(self.centralwidget)
        self.txtnROIsets.setGeometry(QtCore.QRect(605, 30, 71, 21))
        self.txtnROIsets.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtnROIsets.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtnROIsets.setObjectName(_fromUtf8("txtnROIsets"))
        self.tblT2_2 = QtGui.QTableWidget(self.centralwidget)
        self.tblT2_2.setGeometry(QtCore.QRect(35, 605, 1161, 231))
        self.tblT2_2.setMinimumSize(QtCore.QSize(931, 0))
        self.tblT2_2.setObjectName(_fromUtf8("tblT2_2"))
        self.tblT2_2.setColumnCount(14)
        self.tblT2_2.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.tblT2_2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2_2.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2_2.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2_2.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2_2.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2_2.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2_2.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2_2.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2_2.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2_2.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2_2.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2_2.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2_2.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2_2.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2_2.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2_2.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tblT2_2.setHorizontalHeaderItem(13, item)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(45, 615, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setMouseTracking(True)
        self.label_7.setAcceptDrops(True)
        self.label_7.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.txtPhantomName = QtGui.QTextEdit(self.centralwidget)
        self.txtPhantomName.setGeometry(QtCore.QRect(10, 30, 161, 36))
        self.txtPhantomName.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtPhantomName.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtPhantomName.setObjectName(_fromUtf8("txtPhantomName"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(1220, 155, 95, 100))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pbT1ReflectX = QtGui.QPushButton(self.layoutWidget)
        self.pbT1ReflectX.setObjectName(_fromUtf8("pbT1ReflectX"))
        self.verticalLayout.addWidget(self.pbT1ReflectX)
        self.pbT1ReflectY = QtGui.QPushButton(self.layoutWidget)
        self.pbT1ReflectY.setObjectName(_fromUtf8("pbT1ReflectY"))
        self.verticalLayout.addWidget(self.pbT1ReflectY)
        self.pbT1ReflectZ = QtGui.QPushButton(self.layoutWidget)
        self.pbT1ReflectZ.setObjectName(_fromUtf8("pbT1ReflectZ"))
        self.verticalLayout.addWidget(self.pbT1ReflectZ)
        ROIPropertiesGui.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ROIPropertiesGui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1343, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        ROIPropertiesGui.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ROIPropertiesGui)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ROIPropertiesGui.setStatusBar(self.statusbar)
        self.actionOpen_ROI_File = QtGui.QAction(ROIPropertiesGui)
        self.actionOpen_ROI_File.setObjectName(_fromUtf8("actionOpen_ROI_File"))
        self.actionSave_ROI_File = QtGui.QAction(ROIPropertiesGui)
        self.actionSave_ROI_File.setObjectName(_fromUtf8("actionSave_ROI_File"))
        self.menuFile.addAction(self.actionOpen_ROI_File)
        self.menuFile.addAction(self.actionSave_ROI_File)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(ROIPropertiesGui)
        QtCore.QMetaObject.connectSlotsByName(ROIPropertiesGui)

    def retranslateUi(self, ROIPropertiesGui):
        ROIPropertiesGui.setWindowTitle(QtGui.QApplication.translate("ROIPropertiesGui", "ROI Properties", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT1.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "Concentration (mM)", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT1.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "T1(ms)", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT1.verticalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "R1(1/s)", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT1.verticalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "X(mm)", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT1.verticalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "Y(mm)", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT1.verticalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "Z(mm)", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT1.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT1.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT1.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "3", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT1.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "4", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT1.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "5", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT1.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "6", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT1.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "7", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT1.horizontalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "8", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT1.horizontalHeaderItem(8)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "9", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT1.horizontalHeaderItem(9)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "10", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT1.horizontalHeaderItem(10)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "11", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT1.horizontalHeaderItem(11)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "12", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT1.horizontalHeaderItem(12)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "13", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT1.horizontalHeaderItem(13)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ROIPropertiesGui", "T1 Array", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "Concentration (mM)", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "T1(ms)", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2.verticalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "R1(1/s)", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2.verticalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "X(mm)", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2.verticalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "Y(mm)", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2.verticalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "Z(mm)", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "3", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "4", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "5", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "6", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "7", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2.horizontalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "8", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2.horizontalHeaderItem(8)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "9", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2.horizontalHeaderItem(9)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "10", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2.horizontalHeaderItem(10)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "11", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2.horizontalHeaderItem(11)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "12", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2.horizontalHeaderItem(12)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "13", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2.horizontalHeaderItem(13)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ROIPropertiesGui", "T2 Array", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ROIPropertiesGui", "Phantom Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ROIPropertiesGui", "Field (T)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ROIPropertiesGui", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("ROIPropertiesGui", "Temperature (C)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("ROIPropertiesGui", "# of ROI sets", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2_2.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "Concentration (mM)", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2_2.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "T1(ms)", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2_2.verticalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "R1(1/s)", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2_2.verticalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "X(mm)", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2_2.verticalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "Y(mm)", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2_2.verticalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "Z(mm)", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2_2.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2_2.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2_2.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "3", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2_2.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "4", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2_2.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "5", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2_2.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "6", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2_2.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "7", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2_2.horizontalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "8", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2_2.horizontalHeaderItem(8)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "9", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2_2.horizontalHeaderItem(9)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "10", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2_2.horizontalHeaderItem(10)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "11", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2_2.horizontalHeaderItem(11)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "12", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2_2.horizontalHeaderItem(12)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "13", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblT2_2.horizontalHeaderItem(13)
        item.setText(QtGui.QApplication.translate("ROIPropertiesGui", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("ROIPropertiesGui", "PD Array", None, QtGui.QApplication.UnicodeUTF8))
        self.pbT1ReflectX.setText(QtGui.QApplication.translate("ROIPropertiesGui", "reflect on X", None, QtGui.QApplication.UnicodeUTF8))
        self.pbT1ReflectY.setText(QtGui.QApplication.translate("ROIPropertiesGui", "reflect on Y", None, QtGui.QApplication.UnicodeUTF8))
        self.pbT1ReflectZ.setText(QtGui.QApplication.translate("ROIPropertiesGui", "reflect on Z", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("ROIPropertiesGui", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_ROI_File.setText(QtGui.QApplication.translate("ROIPropertiesGui", "Open ROI File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_ROI_File.setText(QtGui.QApplication.translate("ROIPropertiesGui", "Save ROI File", None, QtGui.QApplication.UnicodeUTF8))

